### ISSUE TITLE
Can't throw away garbage

### ISSUE THREAD

**Issue by weirdwater** [evil-moustachio/Ratcycle#1]
Sometimes after picking up garbage, the player can't throw away garbage.
This happens randomly, after working for quite a few times.

**Comment by weirdwater** [comment]
Rat.Pickup() makes _inventory whatever it gets back from GarbageHandler. Which returns null when the GarbageBin is within reach but also if nothing is within reach. So the rat will drop the item, even if there is no bin to catch it.

**Comment by mentosmenno2** [comment]
fixed
